export const Bags = {
    title: "Nike Collections",
    product: "Bag",
    image1 : "assets/Bags/1.avif",
    image2 : "assets/Bags/2.avif",
    image3 : "assets/Bags/3.avif",
    image4 : "assets/Bags/4.avif",
    image5 : "assets/Bags/5.avif",
    name1 : "Nike Hayward",
    name2 : "Nike Heritage",
    name3 : "Nike Aura",
    name4 : "Nike Barsila",
    name5 : "Nike ACG 'DAYMAX' ",
    price1 : "₹ 4295",
    price2 : "₹ 3735",
    price3 : "₹ 5325",
    price4 : "₹ 3015",
    price5 : "₹ 4499",
}